### ISSUE TITLE
SoundFilePLayer example bug?

### ISSUE THREAD

**Issue by ramjsm** [aaronaanderson/ofxATK#1]
Hey! I was trying to build the soundFilePlayer example and I found that nothing was displaying at ofApp.cpp when calling: 

`22    soundFile->draw(20, 20, 400, 180);`

I went into the draw() function at SoundFile.cpp and I changed the following line: 

`32    setDrawPosition(x, y);`

for:

`32    setDrawPosition(newX, newY);`

Everything seems to be working perfectly now. Congrats and thank you very much for this addon!!

**Comment by aaronaanderson** [comment]
Hello @ramjsm, 

I'm always happy when somebody finds a mistake; I'm ecstatic when somebody finds a mistake and also finds the solution! Thank you so much! The library is up to date with the change. 


Aaron
