### ISSUE TITLE
error compiling on linux delay example.

### ISSUE THREAD

**Issue by rdtor** [aaronaanderson/ofxATK#6]
/home/s***/of-workspace/addons/ofxATK/src/modifiers/MoogLadderFilter.h:17:10: fatal error: filters.hpp: No such file or directory
 #include "filters.hpp"
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/shank/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:217: obj/linux64/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/shank/of-workspace/addons/ofxATK/example-Delay'
make: *** [/home/shank/of-workspace/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2

**Comment by ranjithshegde** [comment]
If you are still interested, its a small error in the MoogLadderFilter.h file. Just change the 
#include "filters.hpp"
TO
#include "Filters.hpp"

**Comment by aaronaanderson** [comment]
Thank you @ranjithshegde, and to @rdtor I'm sorry that fixing this got lost on the back burner. Should be good now.
